/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavBar: typeof import('./components/AppNavBar.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    LoginComponent: typeof import('./components/LoginComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VerificationTree: typeof import('./components/VerificationTree.vue')['default']
  }
}
