[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = "2.0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
json = {version = "0.12.4"}
json-core = { path = "../core" }
bincode = "1.3.3"
